name: Pull Request Test

on:
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: test
        run: |
          yarn
          yarn test
